  extends: eslint-config-funkmonkey/typescript-react
  env:
    node: true
    browser: true
  parser: "@typescript-eslint/parser"
  parserOptions:
    project: ./tsconfig.json
  rules:
    '@typescript-eslint/indent': 
      - error
      - 2 
      -
        SwitchCase: 1
        VariableDeclarator: 1
        outerIIFEBody: 1
        FunctionDeclaration:
          parameters: 'first'
          body: 1
        FunctionExpression:
          parameters: 'first'
          body: 1
        CallExpression:
          arguments: 'off'
        ArrayExpression: 1
        ObjectExpression: 1
        ImportDeclaration: 1
        flatTernaryExpressions: false
        ignoredNodes: ['JSXElement', 'JSXElement *']